### ISSUE TITLE
Fazer a documentação do projeto

### ISSUE THREAD

**Issue by gabrielfurlan-dev** [gabrielfurlan-dev/TeamOn#26]
### Descrição

Fazer a documentação do projeto com base no [Arquivo](https://www.notion.so/Teamon-d646a9cb2dc54939addfeac93683bc06?pvs=4#73fe88be664742e3824085c3b0894ada).

**Importante**: Deverá ser entregue até 05/05/2023

**Comment by GabrielGarcia190** [comment]
**Arquivo da documentação disponível em:** https://docs.google.com/document/d/1j6GRrsUZ3Pb-bMIwnGsJkWFas3RQiwt9wG8ogSZNhrY/edit?usp=sharing
